---
  - name: AEM - create {{aem_owner}}
    user:
      name: '{{aem_owner}}'
      comment: '{{aem_owner}} service owner'
      shell: '/sbin/nologin'

  - name: AEM - create /var/log/aem_author.log
    file:
      path: /var/log/aem_author.log
      owner: '{{aem_owner}}'
      group: '{{aem_owner_group}}'
      mode: '0644'
      state: touch

  - name: AEM - add {{aem_server_name}} do /etc/hosts
    shell: 'grep -e "{{aem_server_name}}" /etc/hosts | wc -l'
    register: check_hosts

  - lineinfile:
      dest: /etc/hosts
      line: '{{ansible_eth1.ipv4.address}} {{aem_server_name}}'
      owner: root
      group: root
    when: check_hosts.stdout == '0'

  - name: AEM - check if AEM author instance exists
    stat:
      path: '{{aem_author_docroot}}/crx-quickstart/bin/start'
    register: aem_start_result

  - name: AEM - create project and install
    block:
      - name: AEM - create folder structure
        file:
          path: '{{item}}'
          state: 'directory'
          owner: '{{aem_owner}}'
          group: '{{aem_owner_group}}'
          mode: 0777
        with_items:
          - '{{aem_author_docroot}}'
          - '{{aem_publish_docroot}}'

      - name: AEM - copy AEM archive and licence for author and publish modes
        template:
          src: '{{item.src}}'
          dest: '{{item.dest}}'
          owner: '{{aem_owner}}'
          group: '{{aem_owner_group}}'
          mode: 0777
        with_items:
          - { src: '{{aem_author_jar_source_filename}}', dest: '{{aem_author_docroot}}/{{aem_author_jar_destination_filename}}' }
          - { src: '{{aem_publish_jar_source_filename}}', dest: '{{aem_publish_docroot}}/{{aem_publish_jar_destination_filename}}' }
          - { src: '{{aem_author_license_source_filename}}', dest: '{{aem_author_docroot}}/{{aem_author_license_destination_filename}}' }
          - { src: '{{aem_publish_main_license_source_filename}}', dest: '{{aem_publish_docroot}}/{{aem_publish_main_license_destination_filename}}' }

      - name: AEM - unpack author instance
        command: 'java -jar {{aem_author_docroot}}/{{aem_author_jar_destination_filename}} -unpack -b {{aem_author_docroot}}'
        become: yes
        become_user: '{{aem_owner}}'

      - name: AEM - install aem_author startup service script
        template:
          src: etc/systemd/system/aem_author.service.j2
          dest: /etc/systemd/system/aem_author.service
          owner: root
          group: root
          mode: 0644

      - name: AEM - start AEM author service
        service: name=aem_author state=started

    when: aem_start_result.stat.exists == false

  - name: AEM - install aem_author startup service script
    template:
      src: etc/systemd/system/aem_author.service.j2
      dest: /etc/systemd/system/aem_author.service
      owner: root
      group: root
      mode: 0644

  - name: AEM - install AEM author aem startup service script
    template:
      src: usr/bin/aem_author.j2
      dest: /usr/bin/aem_author
      owner: root
      group: root
      mode: 0644

  - name: AEM - start AEM author service
    service: name=aem_author state=started